apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
  namespace: cloud-ide
type: Opaque
stringData:
  LINUXDO_CLIENT_ID: "XqoDbGtBafVgbZdbLwhkH8oLfhyJtXXS"
  LINUXDO_CLIENT_SECRET: "CIhqgUBBh2wqdRHCyqIDSla4IcjVAor2"
---
# 创建一个ConfigMap用于非敏感的OAuth配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-config
  namespace: cloud-ide
data:
  LINUXDO_BASE_URL: "https://connect.linux.do"
  LINUXDO_REDIRECT_URL: "https://tiantianai.co/auth/oauth/linuxdo/callback"