apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-workspace-68902f525a3bfd0001cf6641
  namespace: cloud-ide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-ide
      workspace: claude-workspace-68902f525a3bfd0001cf6641
  template:
    metadata:
      labels:
        app: cloud-ide
        workspace: claude-workspace-68902f525a3bfd0001cf6641
      annotations:
        sid: "68902f525a3bfd0001cf6641"
        uid: "687700a0fead7a0001abe373"
    spec:
      containers:
      - name: claude-workspace
        image: claude-ai-simple:v2.0-workspace
        imagePullPolicy: Never
        ports:
        - containerPort: 9999
        env:
        - name: WORKSPACE_DIR
          value: "/root/workspace"
        - name: ANTHROPIC_AUTH_TOKEN
          value: "sk-naHryeYkdcR0tapqrO8uNv7dsmeFTnqeSxDPyr8OGVDJZ0Qo"
        - name: ANTHROPIC_BASE_URL
          value: "https://sg.instcopilot-api.com"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: workspace-volume
          mountPath: /root
      volumes:
      - name: workspace-volume
        emptyDir: {}
