apiVersion: v1
kind: Service
metadata:
  name: claude-workspace-nodeport-6890325a5a3bfd0001cf6643
  namespace: cloud-ide
spec:
  type: NodePort
  selector:
    app: cloud-ide
    workspace: claude-workspace-6890325a5a3bfd0001cf6643
  ports:
  - port: 9999
    targetPort: 9999
    nodePort: 31999
  externalTrafficPolicy: Local
