apiVersion: cloud-ide.mangohow.com/v1
kind: WorkSpace
metadata:
  name: test-claude-workspace
  namespace: cloud-ide
spec:
  sid: "68902f525a3bfd0001cf6641"
  uid: "687700a0fead7a0001abe373"
  image: "claude-ai-simple:v2.0-workspace"
  port: 9999
  gitRepository: ""
  mountPath: "/root"
  cpu: "2"
  memory: "2Gi"
  storage: "4Gi"
  operation: "Start"
