apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"LimitRange","metadata":{"annotations":{},"name":"workspace-limit-range","namespace":"cloud-ide-ws"},"spec":{"limits":[{"max":{"cpu":"8","memory":"16Gi"},"min":{"cpu":"100m","memory":"128Mi"},"type":"Pod"},{"default":{"cpu":"1","memory":"1Gi"},"defaultRequest":{"cpu":"500m","memory":"512Mi"},"max":{"cpu":"4","memory":"8Gi"},"min":{"cpu":"100m","memory":"128Mi"},"type":"Container"},{"max":{"storage":"100Gi"},"min":{"storage":"1Gi"},"type":"PersistentVolumeClaim"}]}}
  creationTimestamp: "2025-07-24T04:59:54Z"
  name: workspace-limit-range
  namespace: cloud-ide-ws
  resourceVersion: "1513934"
  uid: 70558f71-8914-42f7-8802-eb3e305265ea
spec:
  limits:
  - max:
      cpu: "8"
      memory: 16Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Pod
  - default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 512Mi
    max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Container
  - max:
      storage: 100Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
